[package]
name = "rlib"
version = "0.1.0"
authors = ["Andrey Sobol <baskerville@andreysobol.com>"]
edition = "2018"

[lib]
name = "myrustlib"
crate-type = ["dylib"]

[dependencies.cpython]
version = "0.3.0"
features = ["extension-module"]